# default videofeed source
default: simulator

cameras:

  - id: simulator
    source: udpsrc port=5600
    #parameters:

  - id: front
    source: /dev/video0
    #parameters:

  - id: rear
    source: /dev/video1
    #parameters:

  - id: down
    source: /dev/video2
    #parameters:




