name: main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tii-communication-link-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      - uses: jfrog/setup-jfrog-cli@v1

      # Run docker build
      - name: Run fog-sw docker build
        run: |
          set -x
          docker build --build-arg BUILD_NUMBER=${GITHUB_RUN_NUMBER} -t communication_link -f Dockerfile .
          container_id=$(docker create communication_link "")
          docker cp ${container_id}:/packages .
          docker rm ${container_id}
          ls -l packages

      - name: Upload to Artifactory
        env:
          JF_ARTIFACTORY_1: ${{ secrets.JF_ARTIFACTORY_SECRET_1 }}
          ARTIFACTORY_URL: ${{ secrets.ARTIFACTORY_URL }}
          ARTIFACTORY_REPO: ${{ secrets.ARTIFACTORY_REPO }}
          DISTRIBUTION: focal
          COMPONENT: fog-sw
          ARCHITECTURE: amd64
          CI: true
        if: github.event_name == 'push'
        run: |
          set -exu
          pkg=$(find packages/ -name 'communication-link*.deb')
          jfrog rt ping --url "$ARTIFACTORY_URL"
          jfrog rt u --url "$ARTIFACTORY_URL" \
                     --deb "$DISTRIBUTION/$COMPONENT/$ARCHITECTURE" \
                     --target-props COMMIT="$GITHUB_SHA" \
                     "$pkg" \
                     "$ARTIFACTORY_REPO"
