name: main

on:
  push:
    branches: main

jobs:
  tii-communication-link-deb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-buildx-action@v1

      # Run docker build
      - name: Run fog-sw docker build
        run: |
          set -x
          docker build --build-arg BUILD_NUMBER=${GITHUB_RUN_NUMBER} -t communication_link -f Dockerfile .
          container_id=$(docker create communication_link "")
          docker cp ${container_id}:/packages .
          docker rm ${container_id}
          ls -l packages
          popd
